* This is it

Basically, this is an initial attempt to get my life organized with a
zettelkasten, in a similar way as it was organized by this German
guy. I think that it's never too late to add some structure in the
madness of living.

Since a long time ago, I was fascinated by sticking my fingers in
various pies, get a cerebral taste of the state of art, and move on to
different experiences. The only constant I can think of in this latter
five years of my life is my fascination with emacs, which seems to be
the only think that have stuck this long with me, and not without
actual merit.

Having said that, I think that I need to study more the way to keep
zettels, something that I don't remember how I am doing in this
repo. It may be with zetteldeft, if this is the proper name of the
project. Or I should probably move to org-roam? I need to check both
and decide what is the best to keep also in a repo, because I think
one of them uses postgres sql, and I'm not sure if the db is
transferable in the repo, or if it can be synced in the various
machines that I keep this sort of diary.

Having said that, I'm off studying about keeping a ``proper''
zettelkasten. I bid you adieu till next time I find it necessary to
update this small readme file.
